"""empty message

Revision ID: cacdcf438024
Revises: 82cc6e45eec5
Create Date: 2023-06-26 03:34:47.963722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacdcf438024'
down_revision = '82cc6e45eec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_roles'),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    # ### end Alembic commands ###
